### ISSUE TITLE
Method Pointer doesnt work

### ISSUE THREAD

**Issue by MystixCode** [mystix-game/server#1]
Method pointer doesnt seem to work in godot4.0.2 alpha with GDExtension. Try it with coming versions again.

multiplayer->connect("peer_connected", Callable(this, "player_connected"));

**Comment by bitcubix** [comment]
you can ignore the error for the moment, the server creation works anyway

**Comment by MystixCode** [comment]
closing cause its an engine issue and works besides throwing an error
